### ISSUE TITLE
if_exists does not drop table when it is set to 'replace'

### ISSUE THREAD

**Issue by deltaoui** [jdglaser/fast-to-sql#1]
I am trying to load a dataframe to database and my code is like the following: 

```
fts.to_sql_fast(self.df, self.schema_name + "." + self.table_name, engine, if_exists='replace', series=False,temp=False)
```
When I execute it the first time it works and creates the table in SQL server. But the second time it throws an error :

` [FreeTDS][SQL Server]There is already an object named 'REF002_SAMPLE_TIME_CSV' in the database. (2714) (SQLExecDirectW)")`

Seems like it doesn't drop the table when it exists ?

**Comment by jdglaser** [comment]
I apologize for the late response.

I'm unable to replicate this issue. My guess is that this issue is coming from lines 119-131:

```python
    # Check if table exists
    try:
        if temp == True:
            engine.execute(("CREATE TABLE #{}"
                        " {};").format(name, col_string_create))
        else:
            engine.execute(("CREATE TABLE {}"
                        " {};").format(name, col_string_create))
        exists = False
    except exc.SQLAlchemyError as e:
        if "there is already an object named" in str(e).lower():
            exists = True
        else:
            raise e
```

Where the function is checking for the specific table already exists error.

Can you please provide the full traceback so I can try to pinpoint where the error is occurring?

**Comment by jdglaser** [comment]
As of release [2.1](https://github.com/jdglaser/fast-to-sql/releases/tag/v2.1) this issue should be fixed. Closing.
