### ISSUE TITLE
OperationalError: ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: An existing connection was forcibly closed by the remote host.\r\n (10054) (SQLExecute); [08S01] [Microsoft][ODBC Driver 17 for SQL Server]Communication link failure (10054)')

### ISSUE THREAD

**Issue by OguzKircicek** [jdglaser/fast-to-sql#14]
How can I solve this problem ? 

OperationalError: ('08S01', '[08S01] [Microsoft][ODBC Driver 17 for SQL Server]TCP Provider: An existing connection was forcibly closed by the remote host.\r\n (10054) (SQLExecute); [08S01] [Microsoft][ODBC Driver 17 for SQL Server]Communication link failure (10054)')

**Comment by jdglaser** [comment]
This looks like a connection issue with the your SQL server. Ensure that you can create a connection with pyodbc and run a basic query against it. For e.g.
```python
conn = <your pyodbc connection>
cur = conn.cursor()
cur.execute("SELECT 1")
```
If you can successfully execute a test query then it could be that SQL Server is forcibly closing a long running transaction. How much data are you trying to upload? How long is the fast_to_sql command running before you experience the error? If it is running for a while, I would try batching the dataset upload to break up the calls to SQL server. This is a feature I want to add to the library, but for now you could implement it easily enough by looping through batches of your result set.

**Comment by jdglaser** [comment]
Closing this as I haven't heard anything and it seems like a connection issue not related to the library
