### ISSUE TITLE
Does not provide support to deal with NaTType(NaN for datetime values) 

### ISSUE THREAD

**Issue by sai-krishna-msk** [jdglaser/fast-to-sql#15]
When i am trying to load a dataframe to sql server, the dataframe consists of Null values for datetime fields, which pandas replaces with NaT(not a time)

Since fast-to-sql is based on pypyodbc, there is a line(as you can see below which produces error)
`
 File "C:\Users\320117176\Anaconda3\envs\scrapeoutlook\lib\site-packages\pypyodbc.py", line 1504, in execute
    datetime_str = param_val.strftime('%Y-%m-%d %H:%M:%S.%f')
`

**Comment by jdglaser** [comment]
This should now be fixed in [Release 2.1.14](https://github.com/jdglaser/fast-to-sql/releases/tag/v2.1.14)
