### ISSUE TITLE
Temporary tables aren't dropped with if_exists='replace'

### ISSUE THREAD

**Issue by PeterJamesLawson** [jdglaser/fast-to-sql#18]
**Temp tables aren't correctly identified, so they don't get dropped when if_exists='replace'.**

`import pyodbc
import pandas as pd
from fast_to_sql import fast_to_sql as fts

data = {'Name': ['Tom', 'nick', 'krish', 'jack'],
        'Age': [20, 21, 19, 18]}
df = pd.DataFrame(data)

conn = pyodbc.connect(driver='{ODBC Driver 17 for SQL Server}',
                      server='MYSERVER',
                      database='MYDB',
                      uid='MYUSER', 
                      pwd='MYPASSWORD',
                      autocommit=True)

cursor = conn.cursor()
cursor.execute("drop table if exists #People")
cursor.execute("create table #People (Name varchar(8) not null, Age int not null)")
cursor.execute("insert into #People (Name, Age) values ('Tom',20), ('nick', 21), ('krish', 19), ('jack', 18)")
cursor.close()

fts.fast_to_sql(df, "People", conn, if_exists="replace", custom={'Name': 'varchar(8) not null', 'Age': 'int not null'}, temp=True, copy=True)
conn.commit()`

Produces this error
![image](https://user-images.githubusercontent.com/45043724/178603647-16fb9e17-1889-47ab-a0de-f0bb0a7abd73.png)

**Comment by PeterJamesLawson** [comment]
@jdglaser I wanted to thank you for this library. 
I use fast-to-sql all the time, and I really appreciate it!

Which is why I put together a pull request (#17) to address some of the problems I'd be using workarounds for up to now.

This is my first time submitting a pull request on github, so apologies if I got carried away with this submission!

**Comment by jdglaser** [comment]
Fixed with pull request #17. Thanks again for contributing!
