### ISSUE TITLE
Pandas Series cannot be pushed due to not having attribute 'select_dtypes'

### ISSUE THREAD

**Issue by Alei35** [jdglaser/fast-to-sql#2]
`fts.to_sql_fast(out_df, "dbo.Table", engine, if_exists="append", series=True)`

results in:

`AttributeError: 'Series' object has no attribute 'select_dtypes'`

**Comment by jdglaser** [comment]
~~Can you paste an example of what out_df looks like?~~

~~I suspect that Pandas is auto-converting it to a series, as it does this when a dataframe is returned with only one column.~~

I've found the issue. I wasn't converting the series to a DF soon enough. If you take lines 42-43:
```python
if series == True:
    df = df.to_frame()
```
and move them up towards the top of the function just after line 24, where the DF is copied it will fix the problem. 

I'll update this issue and upload the new version this week. Thank you for pointing this out.

**Comment by jdglaser** [comment]
Fixed this issue with [update v1.1.3](https://github.com/jdglaser/fast-to-sql/releases/tag/v1.1.3). Closing.
