### ISSUE TITLE
None type

### ISSUE THREAD

**Issue by simbr80** [jdglaser/fast-to-sql#9]
When trying to insert None type data from a pandas dataframe the None type data gets converted to string 'None' which raises an error pyodbc.ProgrammingError: ('String data, right truncation: length 8 buffer 2', 'HY000') since the length of the corresponding sql column is set to nvarchar(1) null

**Comment by simbr80** [comment]
The def _clean_str_cols function converts the None values to strings

I think you could scrap the def _clean_str_cols function, since you are using the parameterized query for inserting data, so "'" shouldn't be an issue.

**Comment by jdglaser** [comment]
Thank you for the feedback. The newest release [2.1.12](https://github.com/jdglaser/fast-to-sql/releases/tag/v2.1.12), should fix this issue.
